version: '3.8'

services:
  minha-aplicacao:
    build: .
    volumes:
      - ${VOLUME_PATH_APP}:/app/applications
      - ${VOLUME_PATH_APP_HELM_VALUE}:/app/applications/values_app
      - ${VOLUME_PATH_SERVICE_HELM_VALUE}:/app/services/values_service
    ports:
      - "10350:10350"
    command: ["bash", "-c", "tilt up && echo 'Acesse a aplicação em http://localhost:10350'"]
