apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
    Name: {{ include "pg.fullname" . }}
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configMap }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}