apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pg.fullname" . }}
  labels:
    {{- include "pg.labels" . | nindent 4 }}
    Name: {{ include "pg.fullname" . }}
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque

data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc }}
{{- end }}