apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: DEV
servers: 1
agents: 2
kubeAPI:
  hostIP: "127.0.0.1"
  hostPort: "6445"
registries:
  create:
    name: registry.localhost
    host: "0.0.0.0"
    hostPort: "5006"